# Generated by Django 4.2 on 2023-05-01 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_userprofile_delete_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='another_phone_number',
            new_name='national_id',
        ),
    ]
