# Generated by Django 4.2.1 on 2023-05-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_rename_another_phone_number_userprofile_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='governrate',
            field=models.CharField(choices=[('CAI', 'Cairo'), ('ALX', 'Alexandria'), ('LUX', 'Luxor'), ('ASN', 'Aswan'), ('MANS', 'Mansoura'), ('DUM', 'Damietta')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vaccine_type',
            field=models.CharField(choices=[('pfizer', 'Pfizer'), ('moderna', 'Moderna'), ('johnson', 'Johnson & Johnson'), ('astrazeneca', 'AstraZeneca')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
